import { Currencies } from 'state/reducers/currency-reducer';
import { InCart } from './firebase-user';

type ProductWithAmount = InCart & {
    discountPercentage: number;
};

export type IpaymuData = {
    sessionId: string;
    paymentNo: string;
    paymentName: string;
    expired: string;
    fee: number;
};

export type ShippingData = {
    shippingDate: Date;
    trackingNum: string;
    shippedBy: string;
};

export interface Order {
    // generated for inner system
    oid: string;
    buyerName: string;
    buyerEmail: string;
    buyerPhone: number;
    buyerUId?: string;
    buyerAddr: string;
    buyerPostal: number;
    // generated for ipaymu!
    total: number;
    currency: Currencies;
    date: Date;
    via?: string;
    channel?: string;
    products: ProductWithAmount[];

    paid: boolean;
    delivered: boolean;

    // generated by ipaymu
    transactionData: IpaymuData;
    shippingData?: ShippingData;
    discountCode?: string;
    discount?: number;
    discountedAmount?: number;

    message?: {
        message: string;
        forName: string;
        fromName: string;
    };
}
